/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mkodiak' at '8/20/16 3:15 PM' with Gradle 3.0
 *
 * @author mkodiak, @date 8/20/16 3:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
